### ISSUE TITLE
Make PAPI placeholders empty for people lacking pronouns!

### ISSUE THREAD

**Issue by newtykins** [lucyy-mc/ProNouns#19]
My server would like to display their pronouns in chat formatting, like so...

![image](https://user-images.githubusercontent.com/19301186/124835649-92b05a80-df79-11eb-874c-8d27ddfe3a5f.png)

This works, and it looks nice - however, it is not so nice for people who are lacking pronouns...

![image](https://user-images.githubusercontent.com/19301186/124835575-74e2f580-df79-11eb-97a6-ad475e0b10f5.png)

I feel like it would be nicer and more practical if the PAPI placeholders were empty for people who had no pronouns, as it would be cleaner, and not much can be done with the unset data!

**Comment by lucyy-mc** [comment]
Will be included in release 1.3.2. For the sake of backwards compatibility, this will be a separate placeholder.

**Comment by lucyy-mc** [comment]
This has been implemented as a placeholder modifier, so you just slap it on the end of a placeholder, for example `%pronouns_pronouns_nounset%`. See the wiki page (https://lucypoulton.net/pronouns/wiki/placeholders) for more info
